name: integration

on:
  push:
    branches: [ master ]
    paths:
      - FORM_Tembelan.Tembelan/**
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout files
      uses: actions/checkout@v2

    - name: Binarize mission
      uses: docker://arwynfr/armake2:alpine
      with:
        entrypoint: /usr/bin/armake2
        args: rapify /github/workspace/FORM_Tembelan.Tembelan/mission.sqm /github/workspace/FORM_Tembelan.Tembelan/mission.bin

    - name: Replace unbinarized file
      run: mv --force FORM_Tembelan.Tembelan/mission.bin FORM_Tembelan.Tembelan/mission.sqm

    - name: Pack mission
      uses: docker://arwynfr/armake2:alpine
      with:
        entrypoint: /usr/bin/armake2
        args: pack /github/workspace/FORM_Tembelan.Tembelan /github/workspace/FORM_Tembelan.Tembelan.pbo

    - name: Stop server
      uses: appleboy/ssh-action@master
      if: github.ref == 'master' && github.event_name == 'push'
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: C:\Arma3\Stop-ArmaInstance -Name 'gsri.krypton'

    - name: Copy mission file to server
      if: github.ref == 'master' && github.event_name == 'push'
      run: |
        apt-get update
        apt-get install --yes openssh-client
        mkdir -p /root/.ssh
        echo "${{ secrets.SSH_HOST_KEY }}" > /root/.ssh/known_hosts
        (umask 077 && echo "${{ secrets.SSH_KEY }}" > /root/.ssh/id_rsa)
        ssh-keygen -y -f /root/.ssh/id_rsa > /root/.ssh/id_rsa.pub
        scp FORM_Tembelan.Tembelan.pbo ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:C:\\Arma3\\master\\mpmissions\\FORM_Tembelan.Tembelan.pbo
      
    - name: Restart server
      uses: appleboy/ssh-action@master
      if: github.ref == 'master' && github.event_name == 'push'
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: Get-ScheduledTask -TaskPath '\Arma\' -TaskName 'gsri.krypton' | Start-ScheduledTask
  